language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t florentb1/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true florentb1/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: ""
  app: "name-of-the-app-on-aws"
  env: "Docker-env"
  bucket_name: ""
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY